import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { fileExists } from "./project-discovery";
import { CI_TRUST_WORKFLOW_RELATIVE_PATH } from "./trust-surface";

/**
 * Scaffolding for the CI re-verification that is the durable anchor of the
 * Agent Trust Surface. Local reconciliation catches mistakes; only a check on
 * a machine the agent does not control survives a scheme-aware in-account
 * rewrite. `trust lock --ci <provider>` writes that workflow so the guarantee
 * is actually wired up, not just documented.
 *
 * The generated workflow is trust-ONLY and pins the CLI to an EXACT version:
 * - trust-only (`trust status --require-lock`, not the full policy check) so it
 *   does not fail on a repo without a package.json and has no dependency-check
 *   coupling;
 * - exact version pin so it can never resolve to a `@latest` CLI that predates
 *   the `trust` command (the "silent no-op anchor" failure mode). The pinned
 *   version is the running CLI's own version, which by construction supports
 *   `trust` — so the workflow works as soon as that version is published.
 */

export type CiProvider = "github";

const SUPPORTED_PROVIDERS: CiProvider[] = ["github"];

export interface CiScaffoldResult {
  status: "created" | "exists";
  path: string;
  /** The exact safeinstall-cli version the workflow pins. */
  pinnedVersion: string;
}

/** The running CLI's version — what the scaffold pins the workflow to. */
function cliVersion(): string {
  return String((require("../package.json") as { version?: string }).version ?? "0.0.0");
}

/** Parse the optional `--ci <provider>` / `--ci=<provider>` flag. */
export function parseCiProvider(argv: string[]): CiProvider | undefined | Error {
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    let value: string | undefined;
    if (token === "--ci") {
      value = argv[index + 1];
      index += 1;
    } else if (token.startsWith("--ci=")) {
      value = token.slice("--ci=".length);
    } else {
      continue;
    }
    if (value === undefined || !SUPPORTED_PROVIDERS.includes(value as CiProvider)) {
      return new Error(
        `Unsupported --ci value ${JSON.stringify(value ?? "")}. Supported: ${SUPPORTED_PROVIDERS.join(", ")}.`
      );
    }
    return value as CiProvider;
  }
  return undefined;
}

const GITHUB_WORKFLOW_RELATIVE_PATH = path.join(...CI_TRUST_WORKFLOW_RELATIVE_PATH.split("/"));

function githubWorkflow(version: string): string {
  return `name: SafeInstall Trust Surface

# Re-verifies the committed Agent Trust Surface baseline (.safeinstall/) on a
# machine the agent does not control. This is the durable anchor: tampering
# with SafeInstall policy, agent hooks, rules files, or MCP configs on a
# compromised local machine does not survive this check.
#
# Generated by \`safeinstall trust lock --ci github\`. The CLI is pinned to an
# exact version on purpose — a floating version could predate the trust
# command and silently pass. Bump it deliberately when you upgrade.
#
# For this to actually enforce, make this a required status check in your
# branch protection, and require review of changes to .safeinstall/ and this
# file (e.g. via CODEOWNERS) — the automatic check catches inconsistent
# tampering; a fully consistent rewrite of the baseline needs human review.
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  trust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install -g safeinstall-cli@${version}
      - run: safeinstall trust status --require-lock
`;
}

/**
 * Write the CI workflow for a provider. Never overwrites an existing file — an
 * existing workflow may be customized, so a re-run reports "exists" and leaves
 * it untouched (idempotent and conservative, like guard setup).
 */
export async function scaffoldCiWorkflow(root: string, _provider: CiProvider): Promise<CiScaffoldResult> {
  // Only GitHub Actions is supported today; parseCiProvider guarantees it.
  const workflowPath = path.join(root, GITHUB_WORKFLOW_RELATIVE_PATH);
  const pinnedVersion = cliVersion();

  if (await fileExists(workflowPath)) {
    return { status: "exists", path: workflowPath, pinnedVersion };
  }

  await mkdir(path.dirname(workflowPath), { recursive: true });
  await writeFile(workflowPath, githubWorkflow(pinnedVersion), "utf8");
  return { status: "created", path: workflowPath, pinnedVersion };
}
