import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { fileExists } from "./project-discovery";

/**
 * Scaffolding for the CI re-verification that is the durable anchor of the
 * Agent Trust Surface. Local reconciliation catches mistakes; only a check on
 * a machine the agent does not control survives a scheme-aware in-account
 * rewrite. `trust lock --ci <provider>` writes that workflow so the guarantee
 * is wired up, not just documented.
 */

export type CiProvider = "github";

const SUPPORTED_PROVIDERS: CiProvider[] = ["github"];

export interface CiScaffoldResult {
  status: "created" | "exists";
  path: string;
}

/** Parse the optional `--ci <provider>` / `--ci=<provider>` flag. */
export function parseCiProvider(argv: string[]): CiProvider | undefined | Error {
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    let value: string | undefined;
    if (token === "--ci") {
      value = argv[index + 1];
      index += 1;
    } else if (token.startsWith("--ci=")) {
      value = token.slice("--ci=".length);
    } else {
      continue;
    }
    if (value === undefined || !SUPPORTED_PROVIDERS.includes(value as CiProvider)) {
      return new Error(
        `Unsupported --ci value ${JSON.stringify(value ?? "")}. Supported: ${SUPPORTED_PROVIDERS.join(", ")}.`
      );
    }
    return value as CiProvider;
  }
  return undefined;
}

const GITHUB_WORKFLOW_RELATIVE_PATH = path.join(".github", "workflows", "safeinstall-trust.yml");

const GITHUB_WORKFLOW = `name: SafeInstall Trust Surface

# Re-verifies the committed Agent Trust Surface baseline (.safeinstall/) on a
# machine the agent does not control. This is the durable anchor: tampering
# with SafeInstall policy, agent hooks, rules files, or MCP configs on a
# compromised local machine does not survive this check.
#
# Generated by \`safeinstall trust lock --ci github\`. Safe to edit; keep the
# verify-trust step so drift fails the build.
on:
  pull_request:
  push:
    branches: [main]

jobs:
  trust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Mickdownunder/SafeInstall@v1
        with:
          verify-trust: "true"
`;

/**
 * Write the CI workflow for a provider. Never overwrites an existing file —
 * an existing workflow may be customized, so a re-run reports "exists" and
 * leaves it untouched (idempotent, conservative, like guard setup).
 */
export async function scaffoldCiWorkflow(root: string, _provider: CiProvider): Promise<CiScaffoldResult> {
  // Only GitHub Actions is supported today; parseCiProvider guarantees it.
  const workflowPath = path.join(root, GITHUB_WORKFLOW_RELATIVE_PATH);

  if (await fileExists(workflowPath)) {
    return { status: "exists", path: workflowPath };
  }

  await mkdir(path.dirname(workflowPath), { recursive: true });
  await writeFile(workflowPath, GITHUB_WORKFLOW, "utf8");
  return { status: "created", path: workflowPath };
}
