/**
 * Curated list of popular npm package names that are frequent typo-squat
 * targets. The list is intentionally hand-maintained for the 0.2.0 release
 * so the shipped tarball has zero network dependencies at runtime.
 *
 * To refresh this list, run `node scripts/refresh-typo-squat-targets.mjs`
 * which pulls a fresh top-N from a known source and updates this file in
 * place. The refresh is run manually before each release, not at build
 * time, so the shipped package is deterministic.
 *
 * Package names are stored lowercase. Scoped packages are included with
 * their scope (e.g. `@types/node`). The list is intentionally focused on
 * unscoped packages since most typo-squat attacks target those.
 */
export const TYPO_SQUAT_TARGETS: readonly string[] = [
  // Frameworks and meta-frameworks
  "react",
  "react-dom",
  "react-native",
  "vue",
  "vuex",
  "vue-router",
  "angular",
  "@angular/core",
  "@angular/common",
  "svelte",
  "sveltekit",
  "preact",
  "solid-js",
  "qwik",
  "astro",
  "next",
  "nuxt",
  "gatsby",
  "remix",
  "@remix-run/react",
  "ember-source",
  "backbone",
  "marko",
  "lit",
  "stencil",

  // Build tools and bundlers
  "webpack",
  "webpack-cli",
  "webpack-dev-server",
  "rollup",
  "esbuild",
  "parcel",
  "vite",
  "turbopack",
  "tsup",
  "swc",
  "@swc/core",
  "@swc/cli",
  "babel",
  "@babel/core",
  "@babel/preset-env",
  "@babel/preset-react",
  "@babel/preset-typescript",
  "rspack",
  "nx",
  "turbo",
  "lerna",
  "changesets",

  // TypeScript
  "typescript",
  "ts-node",
  "tsx",
  "typedoc",
  "tslib",

  // Testing
  "jest",
  "@types/jest",
  "ts-jest",
  "vitest",
  "@vitest/ui",
  "mocha",
  "chai",
  "sinon",
  "ava",
  "tap",
  "tape",
  "jasmine",
  "cypress",
  "playwright",
  "@playwright/test",
  "puppeteer",
  "karma",
  "testing-library",
  "@testing-library/react",
  "@testing-library/jest-dom",
  "@testing-library/vue",
  "@testing-library/user-event",
  "enzyme",
  "jsdom",
  "happy-dom",

  // Linting and formatting
  "eslint",
  "prettier",
  "tslint",
  "stylelint",
  "standard",
  "xo",
  "rome",
  "biome",
  "@biomejs/biome",
  "husky",
  "lint-staged",
  "commitlint",
  "@commitlint/cli",

  // CSS and styling
  "postcss",
  "autoprefixer",
  "tailwindcss",
  "@tailwindcss/forms",
  "@tailwindcss/typography",
  "styled-components",
  "@emotion/react",
  "@emotion/styled",
  "sass",
  "node-sass",
  "less",
  "stylus",
  "cssnano",

  // State management
  "redux",
  "@reduxjs/toolkit",
  "react-redux",
  "mobx",
  "mobx-react",
  "zustand",
  "jotai",
  "recoil",
  "pinia",
  "valtio",
  "xstate",
  "@xstate/react",

  // Routing
  "react-router",
  "react-router-dom",
  "@tanstack/react-router",
  "wouter",

  // Data fetching and HTTP
  "axios",
  "node-fetch",
  "got",
  "request",
  "superagent",
  "cross-fetch",
  "undici",
  "ky",
  "swr",
  "@tanstack/react-query",
  "react-query",
  "apollo-client",
  "@apollo/client",
  "graphql",
  "graphql-request",
  "urql",
  "relay",

  // Utility libraries
  "lodash",
  "lodash-es",
  "underscore",
  "ramda",
  "immer",
  "immutable",
  "rxjs",
  "mitt",
  "eventemitter3",
  "debug",
  "chalk",
  "kleur",
  "picocolors",
  "ansi-colors",
  "colors",

  // Date and time
  "moment",
  "date-fns",
  "dayjs",
  "luxon",

  // Validation and schema
  "zod",
  "yup",
  "joi",
  "ajv",
  "superstruct",
  "io-ts",
  "class-validator",

  // CLI tools
  "commander",
  "yargs",
  "minimist",
  "meow",
  "cac",
  "clipanion",
  "oclif",
  "inquirer",
  "@inquirer/prompts",
  "prompts",
  "enquirer",
  "ora",
  "listr",
  "listr2",
  "boxen",
  "cli-table3",
  "figlet",
  "update-notifier",

  // Node and filesystem
  "@types/node",
  "fs-extra",
  "glob",
  "fast-glob",
  "globby",
  "chokidar",
  "rimraf",
  "mkdirp",
  "cross-spawn",
  "execa",
  "which",
  "dotenv",
  "cross-env",
  "nodemon",

  // Process and concurrency
  "pm2",
  "concurrently",
  "npm-run-all",
  "wait-on",

  // HTTP servers
  "express",
  "koa",
  "fastify",
  "hapi",
  "@hapi/hapi",
  "restify",
  "hono",
  "elysia",
  "polka",
  "body-parser",
  "cookie-parser",
  "cors",
  "helmet",
  "morgan",
  "compression",

  // Databases and ORMs
  "mongoose",
  "sequelize",
  "prisma",
  "@prisma/client",
  "typeorm",
  "drizzle-orm",
  "knex",
  "pg",
  "mysql2",
  "sqlite3",
  "better-sqlite3",
  "redis",
  "ioredis",
  "mongodb",

  // Auth and security
  "bcrypt",
  "bcryptjs",
  "jsonwebtoken",
  "passport",
  "@auth/core",
  "next-auth",
  "uuid",
  "nanoid",
  "crypto-js",

  // Package managers and registries
  "npm",
  "pnpm",
  "yarn",
  "npm-package-arg",
  "semver",
  "npm-registry-fetch",

  // Image and file handling
  "sharp",
  "jimp",
  "multer",
  "formidable",
  "archiver",
  "unzipper",
  "adm-zip",

  // Parsing and serialization
  "yaml",
  "js-yaml",
  "toml",
  "xml2js",
  "fast-xml-parser",
  "csv-parse",
  "papaparse",
  "marked",
  "markdown-it",
  "remark",
  "rehype",
  "cheerio",

  // Websockets and realtime
  "ws",
  "socket.io",
  "socket.io-client",

  // Miscellaneous ecosystem landmarks
  "electron",
  "vscode",
  "monaco-editor",
  "three",
  "phaser",
  "pixi.js",
  "d3",
  "chart.js",
  "plotly.js",
  "leaflet",
  "mapbox-gl",
  "@types/react",
  "@types/react-dom",
  "@types/express",
  "@types/lodash",
  "@types/jest",
  "@types/mocha",
  "@types/node-fetch",
  "@types/semver",

  // SafeInstall self-reference (helps catch typosquats of us!)
  "safeinstall-cli"
];
